#!/bin/bash
#set -x
set -e
shopt -s extglob

# add directory containing this script to PATH
#
export CIROOTDIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
export PATH="$CIROOTDIR/scripts:$CIROOTDIR/configs:$PATH"

print_head()
{
	cat << __END_OF_HEAD__
<head>
<link rel="stylesheet" type="text/css" href="http://www.linaro.org/remote/css/init.css">
<link rel="stylesheet" type="text/css" href="http://www.linaro.org/remote/css/remote.css"></head>
<body>
<div id="content">
<pre style="padding:0 0 0 10;">
<script type="text/javascript">
kernel_name=window.name;
if (!kernel_name) {
	kernel_name=window.parent.document.title;
	kernel_name=kernel_name.split(' ')[0];
	t=kernel_name.split('linux-linaro-')[1];
	if (t)
		kernel_name=t;
}
goodkernel=true;
switch (kernel_name) {
__END_OF_HEAD__
}

print_per()
{
	cat << __END_OF_PER__
case "$SOCFLAVOUR":
	kernel_repo="$kernel_repo";
	kernel_branch="$kernel_branch";
	board_config_repo="$board_config_repo";
	board_config_branch="$board_config_branch";
	ubuntu_and_base_config_repo="$ubuntu_and_base_config_repo";
	ubuntu_and_base_config_branch="$ubuntu_and_base_config_branch";
	board_config_frag="$board_config_frag";
	linaro_ubuntu_packaging_repo="$linaro_ubuntu_packaging_repo";
	linaro_ubuntu_packaging_branch="$linaro_ubuntu_packaging_branch";
	ppaurl="https://code.launchpad.net/~linaro-maintainers/+archive/kernel";
	ppaname="Linaro Kernel PPA";
	maintainermail="mailto:john.rigby@linaro.org"
	maintainername="John Rigby"
	break;
__END_OF_PER__
}

print_foot()
{
	cat << __END_OF_FOOT__
default:
	goodkernel=false;
}
if (goodkernel) {
	document.writeln('Kernel Packaging and Publishing Job for ' + kernel_name);
	document.writeln('  Kernel repo: ' + kernel_repo);
	document.writeln('  Kernel branch: ' + kernel_branch);
	document.writeln('  Board config repo: ' + board_config_repo);
	document.writeln('  Board config branch: ' + board_config_branch);
	document.writeln('  Board config frag: ' + board_config_frag);
	document.writeln('  Ubuntu and base config repo: ' + ubuntu_and_base_config_repo);
	document.writeln('  Ubuntu and base config branch: ' + ubuntu_and_base_config_branch);
	document.writeln('  Linaro ubuntu packaging repo: ' + linaro_ubuntu_packaging_repo);
	document.writeln('  Linaro ubuntu packaging branch: ' + linaro_ubuntu_packaging_branch);
	document.writeln('  PPA: <a target="_blank" href=' + ppaurl + '>' + ppaname + '</a>');
	document.writeln('  Maintainer: <a target="_blank" href=' + maintainermail + '>' + maintainername + '</a>');
} else {
	document.writeln('Kernel Packaging and Publishing Job for unknown kernel: "' + kernel_name + '"');
	document.writeln('kernel name is:');
	document.writeln('  set via name=kernelname in iframe in project description');
	document.writeln('    or');
	document.writeln('  guessed from jenkins project name by removing everthing upto and including "linux-linaro"');
}
</script>
</pre>
</div>
</body>
__END_OF_FOOT__
}

export CFGDIR="$CIROOTDIR/configs"

foreach_kernel_cfg()
{
	for cfg in $CFGDIR/*.cfg
	do
		( source $cfg; eval $1 )
	done
}

print_head
foreach_kernel_cfg print_per
print_foot


exit 0
















